# Generated by Django 2.2.8 on 2022-06-02 17:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20220601_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
